version: '3.8'
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=75nFiVJ7bmro3eDT
      - MEILI_HTTP_PAYLOAD_SIZE_LIMIT=209715200
    volumes:
      - ./meili_data:/meili_data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s