version: '3.8'
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=75nFiVJ7bmro3eDT
      - MEILI_HTTP_PAYLOAD_SIZE_LIMIT=131072000
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped

  meilisearch-ui:
    image: riccoxie/meilisearch-ui:latest
    container_name: meilisearch-ui
    ports:
      - "24900:24900"
    restart: on-failure:5
    depends_on:
      - meilisearch